### ISSUE TITLE
Peer to Peer code Review 

### ISSUE THREAD

**Issue by kerlos-bahaa** [rmiyoyo/Awesome-Books-v2-With-ES6#5]

**Comment by hassanShakur** [comment]
Very nice design & implementation ✅. The code flow is quite appealing. One thing that you can improve on would be making use of functions for tasks that are similar, for example in `books.js` when checking if the user hasn't entered any details. The same can be said for the `index.js` when hiding other pages that are not in view. But the work is nice, keep up 👍.
